-- ═══════════════════════════════════════════════════════════════
-- Seed File: Admin User
-- Description: Creates default admin user for the system
-- ═══════════════════════════════════════════════════════════════

-- Admin User Credentials:
-- Phone: 01024083057
-- Password: Mtd#mora55
-- Role: admin

-- Note: Password will be hashed by the seed script
-- This file is for reference only. Use create-admin.js to create the user.

INSERT INTO users (
  id,
  phone,
  password_hash,
  name,
  role,
  is_active,
  phone_verified,
  email_verified,
  created_at,
  updated_at
) VALUES (
  'b70636cb-b66b-11f0-b501-0a002700000f',
  '01024083057',
  -- Password hash will be generated by the JavaScript seed script
  '$2b$10$placeholder_hash_will_be_replaced_by_script',
  'Admin User',
  'admin',
  1,
  1,
  0,
  NOW(),
  NOW()
) ON DUPLICATE KEY UPDATE
  password_hash = VALUES(password_hash),
  name = VALUES(name),
  role = VALUES(role),
  is_active = VALUES(is_active),
  updated_at = NOW();
