ALTER TABLE videos ADD COLUMN IF NOT EXISTS encryption_key VARCHAR(255) NULL;
ALTER TABLE videos ADD COLUMN IF NOT EXISTS encryption_iv VARCHAR(255) NULL;
ALTER TABLE videos ADD COLUMN IF NOT EXISTS is_encrypted TINYINT(1) DEFAULT 0;
ALTER TABLE videos ADD COLUMN IF NOT EXISTS hls_key VARCHAR(500) NULL;
ALTER TABLE videos ADD COLUMN IF NOT EXISTS qualities_available VARCHAR(500) NULL;
