USE Freelance;

-- Show foreign keys for material_groups table
SELECT 
    CONSTRAINT_NAME,
    TABLE_NAME,
    COLUMN_NAME,
    REFERENCED_TABLE_NAME,
    REFERENCED_COLUMN_NAME
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE TABLE_SCHEMA = 'Freelance'
  AND TABLE_NAME = 'material_groups'
  AND REFERENCED_TABLE_NAME IS NOT NULL;
