-- Create student_fees table for tracking payments
CREATE TABLE IF NOT EXISTS student_fees (
  id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
  student_name VARCHAR(255) NOT NULL,
  phone VARCHAR(50),
  grade_id CHAR(36),
  grade_name VARCHAR(255),
  group_id CHAR(36),
  group_name VARCHAR(255),
  barcode VARCHAR(50),
  amount DECIMAL(10, 2) DEFAULT 0,
  paid_amount DECIMAL(10, 2) DEFAULT 0,
  remaining_amount DECIMAL(10, 2) GENERATED ALWAYS AS (amount - paid_amount) STORED,
  status ENUM('pending', 'partial', 'paid', 'overdue') DEFAULT 'pending',
  payment_method ENUM('cash', 'bank', 'card', 'online') DEFAULT 'cash',
  is_offline BOOLEAN DEFAULT FALSE,
  notes TEXT,
  due_date DATE,
  payment_date DATE,
  receipt_image_url TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (grade_id) REFERENCES grades(id) ON DELETE SET NULL,
  FOREIGN KEY (group_id) REFERENCES `groups`(id) ON DELETE SET NULL,
  INDEX idx_student_name (student_name),
  INDEX idx_phone (phone),
  INDEX idx_status (status),
  INDEX idx_is_offline (is_offline),
  INDEX idx_payment_date (payment_date)
) ENGINE=InnoDB;
